// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Data;

#nullable disable

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241010144331_CreateCategorySeeders2")]
    partial class CreateCategorySeeders2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All electronic products.",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "All clothing products.",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "All books products.",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "All home and garden products.",
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Description = "All sports and outdoor products.",
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 6,
                            Description = "All toys and games products.",
                            Name = "Toys & Games"
                        },
                        new
                        {
                            Id = 7,
                            Description = "All health and beauty products.",
                            Name = "Health & Beauty"
                        },
                        new
                        {
                            Id = 8,
                            Description = "All automotive products.",
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 9,
                            Description = "All office supplies products.",
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 10,
                            Description = "All cooking supplies.",
                            Name = "Cooking"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
